name: Restore NuGet packages using NuGetForUnity
description: Starts the Unity Editor to restore NuGet packages using NuGetForUnity
inputs:
  projectPath:
    required: true
    description: The Unity project path to restore the NuGet packages for
runs:
  using: "docker"
  image: "docker://unityci/editor:ubuntu-2022.2.1f1-windows-mono-1"
  args:
    - bash
    - "-c"

    # 1. activate unity license: from https://github.com/game-ci/unity-test-runner/blob/d982116b88a9a8678875061f6b1163f870135a69/dist/steps/activate.sh
    # 2. run unity editor to restore nuget packages (with -executeMethod NugetForUnity.NugetHelper.Restore)
    - >-
      ACTIVATE_LICENSE_PATH="$GITHUB_WORKSPACE/_activate-license";
      mkdir -p "$ACTIVATE_LICENSE_PATH";
      echo "Changing to \"$ACTIVATE_LICENSE_PATH\" directory.";
      pushd "$ACTIVATE_LICENSE_PATH";
      echo "Requesting activation (personal license)";
      FILE_PATH=UnityLicenseFile.ulf;
      echo "$UNITY_LICENSE" | tr -d '\r' > $FILE_PATH;
      ACTIVATION_OUTPUT=$(unity-editor -batchmode -nographics -logFile /dev/stdout -quit -manualLicenseFile $FILE_PATH);
      UNITY_EXIT_CODE=$?;
      ACTIVATION_SUCCESSFUL=$(echo $ACTIVATION_OUTPUT | grep 'Next license update check is after' | wc -l);
      if [[ $ACTIVATION_SUCCESSFUL -eq 1 ]]; then
        UNITY_EXIT_CODE=0
      fi;
      rm -f $FILE_PATH;
      if [ $UNITY_EXIT_CODE -eq 0 ]; then
        echo "Activation complete.";
      else
        echo "Unclassified error occured while trying to activate license.";
        echo "Exit code was: $UNITY_EXIT_CODE";
        exit $UNITY_EXIT_CODE;
      fi;
      popd;
      unity-editor -quit -batchmode -ignoreCompilerErrors -logfile /dev/stdout
      -projectPath ${{ inputs.projectPath }} -executeMethod NugetForUnity.NugetHelper.Restore;
      rm -r "$ACTIVATE_LICENSE_PATH";
